### PR TITLE
Fixes

### LINKED ISSUE #1855: Cannot compile matlab toolbox (wrapper)
## Description

Cannot compile matlab toolbox but it compiles with no error when toolbox option is off. Seems to have some incompatibility with boost?

## Environment

Ubuntu 22.04, Boost version 1.74.0, MATLAB 2024b

## Additional information
[ 97%] Building CXX object matlab/CMakeFiles/gtsam_matlab_wrapper.dir/__/wrap/gtsam/gtsam_wrapper.cpp.o
In file included from /home/chuan/Downloads/gtsam-4.2/gtsam/nonlinear/Values.h:571,
                 from /home/chuan/Downloads/gtsam-4.2/gtsam/nonlinear/NonlinearFactor.h:24,
                 from /home/chuan/Downloads/gtsam-4.2/gtsam/nonlinear/FunctorizedFactor.h:21,
                 from /home/chuan/Downloads/gtsam-4.2/gtsam/basis/BasisFactors.h:22,
                 from /home/chuan/Downloads/gtsam-4.2/build/wrap/gtsam/gtsam_wrapper.cpp:14:
/home/chuan/Downloads/gtsam-4.2/gtsam/nonlinear/Values-inl.h: In member function ‘gtsam::Values::Filtered<gtsam::Value> gtsam::Values::filter(const std::function<bool(long unsigned int)>&)’:
/home/chuan/Downloads/gtsam-4.2/gtsam/nonlinear/Values-inl.h:253:25: warning: ‘gtsam::Values::Filtered<ValueType> gtsam::Values::filter(const std::function<bool(long unsigned int)>&) [with ValueType = gtsam::Value]’ is deprecated [-Wdeprecated-declarations]
  253 |     return filter<Value>(filterFcn);
      |            ~~~~~~~~~~~~~^~~~~~~~~~~
In file included from /home/chuan/Downloads/gtsam-4.2/gtsam/nonlinear/NonlinearFactor.h:24,
                 from /home/chuan/Downloads/gtsam-4.2/gtsam/nonlinear/FunctorizedFactor.h:21,
                 from /home/chuan/Downloads/gtsam-4.2/gtsam/basis/BasisFactors.h:22,
                 from /home/chuan/Downloads/gtsam-4.2/build/wrap/gtsam/gtsam_wrapper.cpp:14:
/home/chuan/Downloads/gtsam-4.2/gtsam/nonlinear/Values.h:421:5: note: declared here
  421 |     filter(const std::function<bool(Key)>& filterFcn = &_truePredicate<Key>);
      |     ^~~~~~
In file included from /home/chuan/Downloads/gtsam-4.2/gtsam/nonlinear/Values.h:571,
                 from /home/chuan/Downloads/gtsam-4.2/gtsam/nonlinear/NonlinearFactor.h:24,
                 from /home/chuan/Downloads/gtsam-4.2/gtsam/nonlinear/FunctorizedFactor.h:21,
                 from /home/chuan/Downloads/gtsam-4.2/gtsam/basis/BasisFactors.h:22,
                 from /home/chuan/Downloads/gtsam-4.2/build/wrap/gtsam/gtsam_wrapper.cpp:14:
/home/chuan/Downloads/gtsam-4.2/gtsam/nonlinear/Values-inl.h: In member function ‘gtsam::Values::ConstFiltered<gtsam::Value> gtsam::Values::filter(const std::function<bool(long unsigned int)>&) const’:
/home/chuan/Downloads/gtsam-4.2/gtsam/nonlinear/Values-inl.h:265:25: warning: ‘gtsam::Values::ConstFiltered<ValueType> gtsam::Values::filter(const std::function<bool(long unsigned int)>&) const [with ValueType = gtsam::Value]’ is deprecated [-Wdeprecated-declarations]
  265 |     return filter<Value>(filterFcn);
      |            ~~~~~~~~~~~~~^~~~~~~~~~~
In file included from /home/chuan/Downloads/gtsam-4.2/gtsam/nonlinear/NonlinearFactor.h:24,
                 from /home/chuan/Downloads/gtsam-4.2/gtsam/nonlinear/FunctorizedFactor.h:21,
                 from /home/chuan/Downloads/gtsam-4.2/gtsam/basis/BasisFactors.h:22,
                 from /home/chuan/Downloads/gtsam-4.2/build/wrap/gtsam/gtsam_wrapper.cpp:14:
/home/chuan/Downloads/gtsam-4.2/gtsam/nonlinear/Values.h:429:47: note: declared here
  429 |     ConstFiltered<ValueType> GTSAM_DEPRECATED filter(
      |                                               ^~~~~~
In file included from /home/chuan/Downloads/gtsam-4.2/gtsam/discrete/DiscreteBayesNet.h:22,
                 from /home/chuan/Downloads/gtsam-4.2/build/wrap/gtsam/gtsam_wrapper.cpp:22:
/home/chuan/Downloads/gtsam-4.2/gtsam/discrete/DiscreteDistribution.h: In member function ‘size_t gtsam::DiscreteDistribution::solve() const’:
/home/chuan/Downloads/gtsam-4.2/gtsam/discrete/DiscreteDistribution.h:99:56: warning: ‘size_t gtsam::DiscreteConditional::solve(const gtsam::DiscreteValues&) const’ is deprecated [-Wdeprecated-declarations]
   99 |   size_t GTSAM_DEPRECATED solve() const { return Base::solve({}); }
      |                                                        ^~~~~
In file included from /home/chuan/Downloads/gtsam-4.2/gtsam/discrete/DiscreteBayesNet.h:21,
                 from /home/chuan/Downloads/gtsam-4.2/build/wrap/gtsam/gtsam_wrapper.cpp:22:
/home/chuan/Downloads/gtsam-4.2/gtsam/discrete/DiscreteConditional.h:269:27: note: declared here
  269 |   size_t GTSAM_DEPRECATED solve(const DiscreteValues& parentsValues) const;
      |                           ^~~~~
In file included from /home/chuan/Downloads/gtsam-4.2/gtsam/discrete/DiscreteBayesNet.h:22,
                 from /home/chuan/Downloads/gtsam-4.2/build/wrap/gtsam/gtsam_wrapper.cpp:22:
/home/chuan/Downloads/gtsam-4.2/gtsam/discrete/DiscreteDistribution.h:99:61: warning: ‘size_t gtsam::DiscreteConditional::solve(const gtsam::DiscreteValues&) const’ is deprecated [-Wdeprecated-declarations]
   99 |   size_t GTSAM_DEPRECATED solve() const { return Base::solve({}); }
      |                                                  ~~~~~~~~~~~^~~~
In file included from /home/chuan/Downloads/gtsam-4.2/gtsam/discrete/DiscreteBayesNet.h:21,
                 from /home/chuan/Downloads/gtsam-4.2/build/wrap/gtsam/gtsam_wrapper.cpp:22:
/home/chuan/Downloads/gtsam-4.2/gtsam/discrete/DiscreteConditional.h:269:27: note: declared here
  269 |   size_t GTSAM_DEPRECATED solve(const DiscreteValues& parentsValues) const;
      |                           ^~~~~
In file included from /usr/include/boost/smart_ptr/make_shared.hpp:14,
                 from /usr/include/boost/make_shared.hpp:14,
                 from /home/chuan/Downloads/gtsam-4.2/wrap/matlab.h:41,
                 from /home/chuan/Downloads/gtsam-4.2/build/wrap/gtsam/gtsam_wrapper.cpp:1:
/usr/include/boost/smart_ptr/make_shared_object.hpp: In instantiation of ‘typename boost::detail::sp_if_not_array<T>::type boost::make_shared(Args&& ...) [with T = std::pair<gtsam::DiscreteConditional, gtsam::DecisionTreeFactor>; Args = {std::pair<boost::shared_ptr<gtsam::DiscreteConditional>, boost::shared_ptr<gtsam::DecisionTreeFactor> >}; typename boost::detail::sp_if_not_array<T>::type = boost::shared_ptr<std::pair<gtsam::DiscreteConditional, gtsam::DecisionTreeFactor> >]’:
/home/chuan/Downloads/gtsam-4.2/build/wrap/gtsam/gtsam_wrapper.cpp:12189:111:   required from here
**/usr/include/boost/smart_ptr/make_shared_object.hpp:256:5: error: no matching function for call to ‘std::pair<gtsam::DiscreteConditional, gtsam::DecisionTreeFactor>::pair(std::pair<boost::shared_ptr<gtsam::DiscreteConditional>, boost::shared_ptr<gtsam::DecisionTreeFactor> >)’
  256 |     ::new( pv ) T( boost::detail::sp_forward<Args>( args )... );**
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/include/c++/11/bits/stl_algobase.h:64,
                 from /usr/include/c++/11/bits/char_traits.h:39,
                 from /usr/include/c++/11/string:40,
                 from /usr/include/c++/11/bits/locale_classes.h:40,
                 from /usr/include/c++/11/bits/ios_base.h:41,
                 from /usr/include/c++/11/streambuf:41,
                 from /usr/include/c++/11/bits/streambuf_iterator.h:35,
                 from /usr/include/c++/11/iterator:66,
                 from /usr/include/boost/concept_check.hpp:22,
                 from /usr/include/boost/range/concepts.hpp:19,
                 from /home/chuan/Downloads/gtsam-4.2/gtsam/base/types.h:24,
                 from /home/chuan/Downloads/gtsam-4.2/gtsam/global_includes.h:22,
                 from /home/chuan/Downloads/gtsam-4.2/gtsam/base/Vector.h:28,
                 from /home/chuan/Downloads/gtsam-4.2/wrap/matlab.h:25,
                 from /home/chuan/Downloads/gtsam-4.2/build/wrap/gtsam/gtsam_wrapper.cpp:1:
/usr/include/c++/11/bits/stl_pair.h:452:9: note: candidate: ‘template<class ... _Args1, long unsigned int ..._Indexes1, class ... _Args2, long unsigned int ..._Indexes2> std::pair<_T1, _T2>::pair(std::tuple<_Args1 ...>&, std::tuple<_Args2 ...>&, std::_Index_tuple<_Indexes1 ...>, std::_Index_tuple<_Indexes2 ...>) [with _Args1 = {_Args1 ...}; long unsigned int ..._Indexes1 = {_Indexes1 ...}; _Args2 = {_Args2 ...}; long unsigned int ..._Indexes2 = {_Indexes2 ...}; _T1 = gtsam::DiscreteConditional; _T2 = gtsam::DecisionTreeFactor]’
  452 |         pair(tuple<_Args1...>&, tuple<_Args2...>&,
      |         ^~~~
/usr/include/c++/11/bits/stl_pair.h:452:9: note:   template argument deduction/substitution failed:
In file included from /usr/include/boost/smart_ptr/make_shared.hpp:14,
                 from /usr/include/boost/make_shared.hpp:14,
                 from /home/chuan/Downloads/gtsam-4.2/wrap/matlab.h:41,
                 from /home/chuan/Downloads/gtsam-4.2/build/wrap/gtsam/gtsam_wrapper.cpp:1:
/usr/include/boost/smart_ptr/make_shared_object.hpp:256:5: note:   ‘std::pair<boost::shared_ptr<gtsam::DiscreteConditional>, boost::shared_ptr<gtsam::DecisionTreeFactor> >’ is not derived from ‘std::tuple<_Tps ...>’
  256 |     ::new( pv ) T( boost::detail::sp_forward<Args>( args )... );
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/include/c++/11/bits/stl_algobase.h:64,
                 from /usr/include/c++/11/bits/char_traits.h:39,
                 from /usr/include/c++/11/string:40,
                 from /usr/include/c++/11/bits/locale_classes.h:40,
                 from /usr/include/c++/11/bits/ios_base.h:41,
                 from /usr/include/c++/11/streambuf:41,
                 from /usr/include/c++/11/bits/streambuf_iterator.h:35,
                 from /usr/include/c++/11/iterator:66,
                 from /usr/include/boost/concept_check.hpp:22,
                 from /usr/include/boost/range/concepts.hpp:19,
                 from /home/chuan/Downloads/gtsam-4.2/gtsam/base/types.h:24,
                 from /home/chuan/Downloads/gtsam-4.2/gtsam/global_includes.h:22,
                 from /home/chuan/Downloads/gtsam-4.2/gtsam/base/Vector.h:28,
                 from /home/chuan/Downloads/gtsam-4.2/wrap/matlab.h:25,
                 from /home/chuan/Downloads/gtsam-4.2/build/wrap/gtsam/gtsam_wrapper.cpp:1:
/usr/include/c++/11/bits/stl_pair.h:387:9: note: candidate: ‘template<class ... _Args1, class ... _Args2> std::pair<_T1, _T2>::pair(std::piecewise_construct_t, std::tuple<_Args1 ...>, std::tuple<_Args2 ...>) [with _Args1 = {_Args1 ...}; _Args2 = {_Args2 ...}; _T1 = gtsam::DiscreteConditional; _T2 = gtsam::DecisionTreeFactor]’
  387 |         pair(piecewise_construct_t, tuple<_Args1...>, tuple<_Args2...>);
      |         ^~~~
/usr/include/c++/11/bits/stl_pair.h:387:9: note:   template argument deduction/substitution failed:
In file included from /usr/include/boost/smart_ptr/make_shared.hpp:14,
                 from /usr/include/boost/make_shared.hpp:14,
                 from /home/chuan/Downloads/gtsam-4.2/wrap/matlab.h:41,
                 from /home/chuan/Downloads/gtsam-4.2/build/wrap/gtsam/gtsam_wrapper.cpp:1:
/usr/include/boost/smart_ptr/make_shared_object.hpp:256:5: note:   candidate expects 3 arguments, 1 provided
  256 |     ::new( pv ) T( boost::detail::sp_forward<Args>( args )... );
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/include/c++/11/bits/stl_algobase.h:64,
                 from /usr/include/c++/11/bits/char_traits.h:39,
                 from /usr/include/c++/11/string:40,
                 from /usr/include/c++/11/bits/locale_classes.h:40,
                 from /usr/include/c++/11/bits/ios_base.h:41,
                 from /usr/include/c++/11/streambuf:41,
                 from /usr/include/c++/11/bits/streambuf_iterator.h:35,
                 from /usr/include/c++/11/iterator:66,
                 from /usr/include/boost/concept_check.hpp:22,
                 from /usr/include/boost/range/concepts.hpp:19,
                 from /home/chuan/Downloads/gtsam-4.2/gtsam/base/types.h:24,
                 from /home/chuan/Downloads/gtsam-4.2/gtsam/global_includes.h:22,
                 from /home/chuan/Downloads/gtsam-4.2/gtsam/base/Vector.h:28,
                 from /home/chuan/Downloads/gtsam-4.2/wrap/matlab.h:25,
                 from /home/chuan/Downloads/gtsam-4.2/build/wrap/gtsam/gtsam_wrapper.cpp:1:
/usr/include/c++/11/bits/stl_pair.h:381:28: note: candidate: ‘template<class _U1, class _U2, typename std::enable_if<(std::_PCC<((! std::is_same<gtsam::DiscreteConditional, _U1>::value) || (! std::is_same<gtsam::DecisionTreeFactor, _U2>::value)), gtsam::DiscreteConditional, gtsam::DecisionTreeFactor>::_MoveConstructiblePair<_U1, _U2>() && (! std::_PCC<((! std::is_same<gtsam::DiscreteConditional, _U1>::value) || (! std::is_same<gtsam::DecisionTreeFactor, _U2>::value)), gtsam::DiscreteConditional, gtsam::DecisionTreeFactor>::_ImplicitlyMoveConvertiblePair<_U1, _U2>())), bool>::type <anonymous> > constexpr std::pair<_T1, _T2>::pair(std::pair<_U1, _U2>&&) [with _U1 = _U1; _U2 = _U2; typename std::enable_if<(std::_PCC<((! std::is_same<_T1, _U1>::value) || (! std::is_same<_T2, _U2>::value)), _T1, _T2>::_MoveConstructiblePair<_U1, _U2>() && (! std::_PCC<((! std::is_same<_T1, _U1>::value) || (! std::is_same<_T2, _U2>::value)), _T1, _T2>::_ImplicitlyMoveConvertiblePair<_U1, _U2>())), bool>::type <anonymous> = <anonymous>; _T1 = gtsam::DiscreteConditional; _T2 = gtsam::DecisionTreeFactor]’
  381 |         explicit constexpr pair(pair<_U1, _U2>&& __p)
      |                            ^~~~
/usr/include/c++/11/bits/stl_pair.h:381:28: note:   template argument deduction/substitution failed:
/usr/include/c++/11/bits/stl_pair.h:380:38: error: no type named ‘type’ in ‘struct std::enable_if<false, bool>’
  380 |                          bool>::type=false>
      |                                      ^~~~~
/usr/include/c++/11/bits/stl_pair.h:371:19: note: candidate: ‘template<class _U1, class _U2, typename std::enable_if<(std::_PCC<((! std::is_same<gtsam::DiscreteConditional, _U1>::value) || (! std::is_same<gtsam::DecisionTreeFactor, _U2>::value)), gtsam::DiscreteConditional, gtsam::DecisionTreeFactor>::_MoveConstructiblePair<_U1, _U2>() && std::_PCC<((! std::is_same<gtsam::DiscreteConditional, _U1>::value) || (! std::is_same<gtsam::DecisionTreeFactor, _U2>::value)), gtsam::DiscreteConditional, gtsam::DecisionTreeFactor>::_ImplicitlyMoveConvertiblePair<_U1, _U2>()), bool>::type <anonymous> > constexpr std::pair<_T1, _T2>::pair(std::pair<_U1, _U2>&&) [with _U1 = _U1; _U2 = _U2; typename std::enable_if<(std::_PCC<((! std::is_same<_T1, _U1>::value) || (! std::is_same<_T2, _U2>::value)), _T1, _T2>::_MoveConstructiblePair<_U1, _U2>() && std::_PCC<((! std::is_same<_T1, _U1>::value) || (! std::is_same<_T2, _U2>::value)), _T1, _T2>::_ImplicitlyMoveConvertiblePair<_U1, _U2>()), bool>::type <anonymous> = <anonymous>; _T1 = gtsam::DiscreteConditional; _T2 = gtsam::DecisionTreeFactor]’
  371 |         constexpr pair(pair<_U1, _U2>&& __p)
      |                   ^~~~
/usr/include/c++/11/bits/stl_pair.h:371:19: note:   template argument deduction/substitution failed:
/usr/include/c++/11/bits/stl_pair.h:370:38: error: no type named ‘type’ in ‘struct std::enable_if<false, bool>’
  370 |                          bool>::type=true>
      |                                      ^~~~
/usr/include/c++/11/bits/stl_pair.h:361:28: note: candidate: ‘template<class _U1, class _U2, typename std::enable_if<(_MoveConstructiblePair<_U1, _U2>() && (! _ImplicitlyMoveConvertiblePair<_U1, _U2>())), bool>::type <anonymous> > constexpr std::pair<_T1, _T2>::pair(_U1&&, _U2&&) [with _U1 = _U1; _U2 = _U2; typename std::enable_if<(std::_PCC<true, _T1, _T2>::_MoveConstructiblePair<_U1, _U2>() && (! std::_PCC<true, _T1, _T2>::_ImplicitlyMoveConvertiblePair<_U1, _U2>())), bool>::type <anonymous> = <anonymous>; _T1 = gtsam::DiscreteConditional; _T2 = gtsam::DecisionTreeFactor]’
  361 |         explicit constexpr pair(_U1&& __x, _U2&& __y)
      |                            ^~~~
/usr/include/c++/11/bits/stl_pair.h:361:28: note:   template argument deduction/substitution failed:
In file included from /usr/include/boost/smart_ptr/make_shared.hpp:14,
                 from /usr/include/boost/make_shared.hpp:14,
                 from /home/chuan/Downloads/gtsam-4.2/wrap/matlab.h:41,
                 from /home/chuan/Downloads/gtsam-4.2/build/wrap/gtsam/gtsam_wrapper.cpp:1:
/usr/include/boost/smart_ptr/make_shared_object.hpp:256:5: note:   candidate expects 2 arguments, 1 provided
  256 |     ::new( pv ) T( boost::detail::sp_forward<Args>( args )... );
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/include/c++/11/bits/stl_algobase.h:64,
                 from /usr/include/c++/11/bits/char_traits.h:39,
                 from /usr/include/c++/11/string:40,
                 from /usr/include/c++/11/bits/locale_classes.h:40,
                 from /usr/include/c++/11/bits/ios_base.h:41,
                 from /usr/include/c++/11/streambuf:41,
                 from /usr/include/c++/11/bits/streambuf_iterator.h:35,
                 from /usr/include/c++/11/iterator:66,
                 from /usr/include/boost/concept_check.hpp:22,
                 from /usr/include/boost/range/concepts.hpp:19,
                 from /home/chuan/Downloads/gtsam-4.2/gtsam/base/types.h:24,
                 from /home/chuan/Downloads/gtsam-4.2/gtsam/global_includes.h:22,
                 from /home/chuan/Downloads/gtsam-4.2/gtsam/base/Vector.h:28,
                 from /home/chuan/Downloads/gtsam-4.2/wrap/matlab.h:25,
                 from /home/chuan/Downloads/gtsam-4.2/build/wrap/gtsam/gtsam_wrapper.cpp:1:
/usr/include/c++/11/bits/stl_pair.h:352:19: note: candidate: ‘template<class _U1, class _U2, typename std::enable_if<(_MoveConstructiblePair<_U1, _U2>() && _ImplicitlyMoveConvertiblePair<_U1, _U2>()), bool>::type <anonymous> > constexpr std::pair<_T1, _T2>::pair(_U1&&, _U2&&) [with _U1 = _U1; _U2 = _U2; typename std::enable_if<(std::_PCC<true, _T1, _T2>::_MoveConstructiblePair<_U1, _U2>() && std::_PCC<true, _T1, _T2>::_ImplicitlyMoveConvertiblePair<_U1, _U2>()), bool>::type <anonymous> = <anonymous>; _T1 = gtsam::DiscreteConditional; _T2 = gtsam::DecisionTreeFactor]’
  352 |         constexpr pair(_U1&& __x, _U2&& __y)
      |                   ^~~~
/usr/include/c++/11/bits/stl_pair.h:352:19: note:   template argument deduction/substitution failed:
In file included from /usr/include/boost/smart_ptr/make_shared.hpp:14,
                 from /usr/include/boost/make_shared.hpp:14,
                 from /home/chuan/Downloads/gtsam-4.2/wrap/matlab.h:41,
                 from /home/chuan/Downloads/gtsam-4.2/build/wrap/gtsam/gtsam_wrapper.cpp:1:
/usr/include/boost/smart_ptr/make_shared_object.hpp:256:5: note:   candidate expects 2 arguments, 1 provided
  256 |     ::new( pv ) T( boost::detail::sp_forward<Args>( args )... );
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/include/c++/11/bits/stl_algobase.h:64,
                 from /usr/include/c++/11/bits/char_traits.h:39,
                 from /usr/include/c++/11/string:40,
                 from /usr/include/c++/11/bits/locale_classes.h:40,
                 from /usr/include/c++/11/bits/ios_base.h:41,
                 from /usr/include/c++/11/streambuf:41,
                 from /usr/include/c++/11/bits/streambuf_iterator.h:35,
                 from /usr/include/c++/11/iterator:66,
                 from /usr/include/boost/concept_check.hpp:22,
                 from /usr/include/boost/range/concepts.hpp:19,
                 from /home/chuan/Downloads/gtsam-4.2/gtsam/base/types.h:24,
                 from /home/chuan/Downloads/gtsam-4.2/gtsam/global_includes.h:22,
                 from /home/chuan/Downloads/gtsam-4.2/gtsam/base/Vector.h:28,
                 from /home/chuan/Downloads/gtsam-4.2/wrap/matlab.h:25,
                 from /home/chuan/Downloads/gtsam-4.2/build/wrap/gtsam/gtsam_wrapper.cpp:1:
/usr/include/c++/11/bits/stl_pair.h:343:17: note: candidate: ‘template<class _U2, typename std::enable_if<_CopyMovePair<false, gtsam::DiscreteConditional, _U2>(), bool>::type <anonymous> > std::pair<_T1, _T2>::pair(const _T1&, _U2&&) [with _U2 = _U2; typename std::enable_if<std::_PCC<true, _T1, _T2>::_CopyMovePair<false, _T1, _U2>(), bool>::type <anonymous> = <anonymous>; _T1 = gtsam::DiscreteConditional; _T2 = gtsam::DecisionTreeFactor]’
  343 |        explicit pair(const _T1& __x, _U2&& __y)
      |                 ^~~~
/usr/include/c++/11/bits/stl_pair.h:343:17: note:   template argument deduction/substitution failed:
In file included from /usr/include/boost/smart_ptr/make_shared.hpp:14,
                 from /usr/include/boost/make_shared.hpp:14,
                 from /home/chuan/Downloads/gtsam-4.2/wrap/matlab.h:41,
                 from /home/chuan/Downloads/gtsam-4.2/build/wrap/gtsam/gtsam_wrapper.cpp:1:
/usr/include/boost/smart_ptr/make_shared_object.hpp:256:5: note:   candidate expects 2 arguments, 1 provided
  256 |     ::new( pv ) T( boost::detail::sp_forward<Args>( args )... );
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/include/c++/11/bits/stl_algobase.h:64,
                 from /usr/include/c++/11/bits/char_traits.h:39,
                 from /usr/include/c++/11/string:40,
                 from /usr/include/c++/11/bits/locale_classes.h:40,
                 from /usr/include/c++/11/bits/ios_base.h:41,
                 from /usr/include/c++/11/streambuf:41,
                 from /usr/include/c++/11/bits/streambuf_iterator.h:35,
                 from /usr/include/c++/11/iterator:66,
                 from /usr/include/boost/concept_check.hpp:22,
                 from /usr/include/boost/range/concepts.hpp:19,
                 from /home/chuan/Downloads/gtsam-4.2/gtsam/base/types.h:24,
                 from /home/chuan/Downloads/gtsam-4.2/gtsam/global_includes.h:22,
                 from /home/chuan/Downloads/gtsam-4.2/gtsam/base/Vector.h:28,
                 from /home/chuan/Downloads/gtsam-4.2/wrap/matlab.h:25,
                 from /home/chuan/Downloads/gtsam-4.2/build/wrap/gtsam/gtsam_wrapper.cpp:1:
/usr/include/c++/11/bits/stl_pair.h:336:18: note: candidate: ‘template<class _U2, typename std::enable_if<_CopyMovePair<true, gtsam::DiscreteConditional, _U2>(), bool>::type <anonymous> > constexpr std::pair<_T1, _T2>::pair(const _T1&, _U2&&) [with _U2 = _U2; typename std::enable_if<std::_PCC<true, _T1, _T2>::_CopyMovePair<true, _T1, _U2>(), bool>::type <anonymous> = <anonymous>; _T1 = gtsam::DiscreteConditional; _T2 = gtsam::DecisionTreeFactor]’
  336 |        constexpr pair(const _T1& __x, _U2&& __y)
      |                  ^~~~
/usr/include/c++/11/bits/stl_pair.h:336:18: note:   template argument deduction/substitution failed:
In file included from /usr/include/boost/smart_ptr/make_shared.hpp:14,
                 from /usr/include/boost/make_shared.hpp:14,
                 from /home/chuan/Downloads/gtsam-4.2/wrap/matlab.h:41,
                 from /home/chuan/Downloads/gtsam-4.2/build/wrap/gtsam/gtsam_wrapper.cpp:1:
/usr/include/boost/smart_ptr/make_shared_object.hpp:256:5: note:   candidate expects 2 arguments, 1 provided
  256 |     ::new( pv ) T( boost::detail::sp_forward<Args>( args )... );
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/include/c++/11/bits/stl_algobase.h:64,
                 from /usr/include/c++/11/bits/char_traits.h:39,
                 from /usr/include/c++/11/string:40,
                 from /usr/include/c++/11/bits/locale_classes.h:40,
                 from /usr/include/c++/11/bits/ios_base.h:41,
                 from /usr/include/c++/11/streambuf:41,
                 from /usr/include/c++/11/bits/streambuf_iterator.h:35,
                 from /usr/include/c++/11/iterator:66,
                 from /usr/include/boost/concept_check.hpp:22,
                 from /usr/include/boost/range/concepts.hpp:19,
                 from /home/chuan/Downloads/gtsam-4.2/gtsam/base/types.h:24,
                 from /home/chuan/Downloads/gtsam-4.2/gtsam/global_includes.h:22,
                 from /home/chuan/Downloads/gtsam-4.2/gtsam/base/Vector.h:28,
                 from /home/chuan/Downloads/gtsam-4.2/wrap/matlab.h:25,
                 from /home/chuan/Downloads/gtsam-4.2/build/wrap/gtsam/gtsam_wrapper.cpp:1:
/usr/include/c++/11/bits/stl_pair.h:329:27: note: candidate: ‘template<class _U1, typename std::enable_if<_MoveCopyPair<false, _U1, gtsam::DecisionTreeFactor>(), bool>::type <anonymous> > constexpr std::pair<_T1, _T2>::pair(_U1&&, const _T2&) [with _U1 = _U1; typename std::enable_if<std::_PCC<true, _T1, _T2>::_MoveCopyPair<false, _U1, _T2>(), bool>::type <anonymous> = <anonymous>; _T1 = gtsam::DiscreteConditional; _T2 = gtsam::DecisionTreeFactor]’
  329 |        explicit constexpr pair(_U1&& __x, const _T2& __y)
      |                           ^~~~
/usr/include/c++/11/bits/stl_pair.h:329:27: note:   template argument deduction/substitution failed:
In file included from /usr/include/boost/smart_ptr/make_shared.hpp:14,
                 from /usr/include/boost/make_shared.hpp:14,
                 from /home/chuan/Downloads/gtsam-4.2/wrap/matlab.h:41,
                 from /home/chuan/Downloads/gtsam-4.2/build/wrap/gtsam/gtsam_wrapper.cpp:1:
/usr/include/boost/smart_ptr/make_shared_object.hpp:256:5: note:   candidate expects 2 arguments, 1 provided
  256 |     ::new( pv ) T( boost::detail::sp_forward<Args>( args )... );
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/include/c++/11/bits/stl_algobase.h:64,
                 from /usr/include/c++/11/bits/char_traits.h:39,
                 from /usr/include/c++/11/string:40,
                 from /usr/include/c++/11/bits/locale_classes.h:40,
                 from /usr/include/c++/11/bits/ios_base.h:41,
                 from /usr/include/c++/11/streambuf:41,
                 from /usr/include/c++/11/bits/streambuf_iterator.h:35,
                 from /usr/include/c++/11/iterator:66,
                 from /usr/include/boost/concept_check.hpp:22,
                 from /usr/include/boost/range/concepts.hpp:19,
                 from /home/chuan/Downloads/gtsam-4.2/gtsam/base/types.h:24,
                 from /home/chuan/Downloads/gtsam-4.2/gtsam/global_includes.h:22,
                 from /home/chuan/Downloads/gtsam-4.2/gtsam/base/Vector.h:28,
                 from /home/chuan/Downloads/gtsam-4.2/wrap/matlab.h:25,
                 from /home/chuan/Downloads/gtsam-4.2/build/wrap/gtsam/gtsam_wrapper.cpp:1:
/usr/include/c++/11/bits/stl_pair.h:322:18: note: candidate: ‘template<class _U1, typename std::enable_if<_MoveCopyPair<true, _U1, gtsam::DecisionTreeFactor>(), bool>::type <anonymous> > constexpr std::pair<_T1, _T2>::pair(_U1&&, const _T2&) [with _U1 = _U1; typename std::enable_if<std::_PCC<true, _T1, _T2>::_MoveCopyPair<true, _U1, _T2>(), bool>::type <anonymous> = <anonymous>; _T1 = gtsam::DiscreteConditional; _T2 = gtsam::DecisionTreeFactor]’
  322 |        constexpr pair(_U1&& __x, const _T2& __y)
      |                  ^~~~
/usr/include/c++/11/bits/stl_pair.h:322:18: note:   template argument deduction/substitution failed:
In file included from /usr/include/boost/smart_ptr/make_shared.hpp:14,
                 from /usr/include/boost/make_shared.hpp:14,
                 from /home/chuan/Downloads/gtsam-4.2/wrap/matlab.h:41,
                 from /home/chuan/Downloads/gtsam-4.2/build/wrap/gtsam/gtsam_wrapper.cpp:1:
/usr/include/boost/smart_ptr/make_shared_object.hpp:256:5: note:   candidate expects 2 arguments, 1 provided
  256 |     ::new( pv ) T( boost::detail::sp_forward<Args>( args )... );
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/include/c++/11/bits/stl_algobase.h:64,
                 from /usr/include/c++/11/bits/char_traits.h:39,
                 from /usr/include/c++/11/string:40,
                 from /usr/include/c++/11/bits/locale_classes.h:40,
                 from /usr/include/c++/11/bits/ios_base.h:41,
                 from /usr/include/c++/11/streambuf:41,
                 from /usr/include/c++/11/bits/streambuf_iterator.h:35,
                 from /usr/include/c++/11/iterator:66,
                 from /usr/include/boost/concept_check.hpp:22,
                 from /usr/include/boost/range/concepts.hpp:19,
                 from /home/chuan/Downloads/gtsam-4.2/gtsam/base/types.h:24,
                 from /home/chuan/Downloads/gtsam-4.2/gtsam/global_includes.h:22,
                 from /home/chuan/Downloads/gtsam-4.2/gtsam/base/Vector.h:28,
                 from /home/chuan/Downloads/gtsam-4.2/wrap/matlab.h:25,
                 from /home/chuan/Downloads/gtsam-4.2/build/wrap/gtsam/gtsam_wrapper.cpp:1:
/usr/include/c++/11/bits/stl_pair.h:309:28: note: candidate: ‘template<class _U1, class _U2, typename std::enable_if<(std::_PCC<((! std::is_same<gtsam::DiscreteConditional, _U1>::value) || (! std::is_same<gtsam::DecisionTreeFactor, _U2>::value)), gtsam::DiscreteConditional, gtsam::DecisionTreeFactor>::_ConstructiblePair<_U1, _U2>() && (! std::_PCC<((! std::is_same<gtsam::DiscreteConditional, _U1>::value) || (! std::is_same<gtsam::DecisionTreeFactor, _U2>::value)), gtsam::DiscreteConditional, gtsam::DecisionTreeFactor>::_ImplicitlyConvertiblePair<_U1, _U2>())), bool>::type <anonymous> > constexpr std::pair<_T1, _T2>::pair(const std::pair<_U1, _U2>&) [with _U1 = _U1; _U2 = _U2; typename std::enable_if<(std::_PCC<((! std::is_same<_T1, _U1>::value) || (! std::is_same<_T2, _U2>::value)), _T1, _T2>::_ConstructiblePair<_U1, _U2>() && (! std::_PCC<((! std::is_same<_T1, _U1>::value) || (! std::is_same<_T2, _U2>::value)), _T1, _T2>::_ImplicitlyConvertiblePair<_U1, _U2>())), bool>::type <anonymous> = <anonymous>; _T1 = gtsam::DiscreteConditional; _T2 = gtsam::DecisionTreeFactor]’
  309 |         explicit constexpr pair(const pair<_U1, _U2>& __p)
      |                            ^~~~
/usr/include/c++/11/bits/stl_pair.h:309:28: note:   template argument deduction/substitution failed:
/usr/include/c++/11/bits/stl_pair.h:308:38: error: no type named ‘type’ in ‘struct std::enable_if<false, bool>’
  308 |                          bool>::type=false>
      |                                      ^~~~~
/usr/include/c++/11/bits/stl_pair.h:300:19: note: candidate: ‘template<class _U1, class _U2, typename std::enable_if<(std::_PCC<((! std::is_same<gtsam::DiscreteConditional, _U1>::value) || (! std::is_same<gtsam::DecisionTreeFactor, _U2>::value)), gtsam::DiscreteConditional, gtsam::DecisionTreeFactor>::_ConstructiblePair<_U1, _U2>() && std::_PCC<((! std::is_same<gtsam::DiscreteConditional, _U1>::value) || (! std::is_same<gtsam::DecisionTreeFactor, _U2>::value)), gtsam::DiscreteConditional, gtsam::DecisionTreeFactor>::_ImplicitlyConvertiblePair<_U1, _U2>()), bool>::type <anonymous> > constexpr std::pair<_T1, _T2>::pair(const std::pair<_U1, _U2>&) [with _U1 = _U1; _U2 = _U2; typename std::enable_if<(std::_PCC<((! std::is_same<_T1, _U1>::value) || (! std::is_same<_T2, _U2>::value)), _T1, _T2>::_ConstructiblePair<_U1, _U2>() && std::_PCC<((! std::is_same<_T1, _U1>::value) || (! std::is_same<_T2, _U2>::value)), _T1, _T2>::_ImplicitlyConvertiblePair<_U1, _U2>()), bool>::type <anonymous> = <anonymous>; _T1 = gtsam::DiscreteConditional; _T2 = gtsam::DecisionTreeFactor]’
  300 |         constexpr pair(const pair<_U1, _U2>& __p)
      |                   ^~~~
/usr/include/c++/11/bits/stl_pair.h:300:19: note:   template argument deduction/substitution failed:
/usr/include/c++/11/bits/stl_pair.h:299:39: error: no type named ‘type’ in ‘struct std::enable_if<false, bool>’
  299 |                           bool>::type=true>
      |                                       ^~~~
/usr/include/c++/11/bits/stl_pair.h:276:26: note: candidate: ‘template<class _U1, class _U2, typename std::enable_if<(_ConstructiblePair<_U1, _U2>() && (! _ImplicitlyConvertiblePair<_U1, _U2>())), bool>::type <anonymous> > constexpr std::pair<_T1, _T2>::pair(const _T1&, const _T2&) [with _U1 = _U1; _U2 = _U2; typename std::enable_if<(std::_PCC<true, _T1, _T2>::_ConstructiblePair<_U1, _U2>() && (! std::_PCC<true, _T1, _T2>::_ImplicitlyConvertiblePair<_U1, _U2>())), bool>::type <anonymous> = <anonymous>; _T1 = gtsam::DiscreteConditional; _T2 = gtsam::DecisionTreeFactor]’
  276 |       explicit constexpr pair(const _T1& __a, const _T2& __b)
      |                          ^~~~
/usr/include/c++/11/bits/stl_pair.h:276:26: note:   template argument deduction/substitution failed:
In file included from /usr/include/boost/smart_ptr/make_shared.hpp:14,
                 from /usr/include/boost/make_shared.hpp:14,
                 from /home/chuan/Downloads/gtsam-4.2/wrap/matlab.h:41,
                 from /home/chuan/Downloads/gtsam-4.2/build/wrap/gtsam/gtsam_wrapper.cpp:1:
/usr/include/boost/smart_ptr/make_shared_object.hpp:256:5: note:   candidate expects 2 arguments, 1 provided
  256 |     ::new( pv ) T( boost::detail::sp_forward<Args>( args )... );
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/include/c++/11/bits/stl_algobase.h:64,
                 from /usr/include/c++/11/bits/char_traits.h:39,
                 from /usr/include/c++/11/string:40,
                 from /usr/include/c++/11/bits/locale_classes.h:40,
                 from /usr/include/c++/11/bits/ios_base.h:41,
                 from /usr/include/c++/11/streambuf:41,
                 from /usr/include/c++/11/bits/streambuf_iterator.h:35,
                 from /usr/include/c++/11/iterator:66,
                 from /usr/include/boost/concept_check.hpp:22,
                 from /usr/include/boost/range/concepts.hpp:19,
                 from /home/chuan/Downloads/gtsam-4.2/gtsam/base/types.h:24,
                 from /home/chuan/Downloads/gtsam-4.2/gtsam/global_includes.h:22,
                 from /home/chuan/Downloads/gtsam-4.2/gtsam/base/Vector.h:28,
                 from /home/chuan/Downloads/gtsam-4.2/wrap/matlab.h:25,
                 from /home/chuan/Downloads/gtsam-4.2/build/wrap/gtsam/gtsam_wrapper.cpp:1:
/usr/include/c++/11/bits/stl_pair.h:266:17: note: candidate: ‘template<class _U1, class _U2, typename std::enable_if<(_ConstructiblePair<_U1, _U2>() && _ImplicitlyConvertiblePair<_U1, _U2>()), bool>::type <anonymous> > constexpr std::pair<_T1, _T2>::pair(const _T1&, const _T2&) [with _U1 = _U1; _U2 = _U2; typename std::enable_if<(std::_PCC<true, _T1, _T2>::_ConstructiblePair<_U1, _U2>() && std::_PCC<true, _T1, _T2>::_ImplicitlyConvertiblePair<_U1, _U2>()), bool>::type <anonymous> = <anonymous>; _T1 = gtsam::DiscreteConditional; _T2 = gtsam::DecisionTreeFactor]’
  266 |       constexpr pair(const _T1& __a, const _T2& __b)
      |                 ^~~~
/usr/include/c++/11/bits/stl_pair.h:266:17: note:   template argument deduction/substitution failed:
In file included from /usr/include/boost/smart_ptr/make_shared.hpp:14,
                 from /usr/include/boost/make_shared.hpp:14,
                 from /home/chuan/Downloads/gtsam-4.2/wrap/matlab.h:41,
                 from /home/chuan/Downloads/gtsam-4.2/build/wrap/gtsam/gtsam_wrapper.cpp:1:
/usr/include/boost/smart_ptr/make_shared_object.hpp:256:5: note:   candidate expects 2 arguments, 1 provided
  256 |     ::new( pv ) T( boost::detail::sp_forward<Args>( args )... );
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/include/c++/11/bits/stl_algobase.h:64,
                 from /usr/include/c++/11/bits/char_traits.h:39,
                 from /usr/include/c++/11/string:40,
                 from /usr/include/c++/11/bits/locale_classes.h:40,
                 from /usr/include/c++/11/bits/ios_base.h:41,
                 from /usr/include/c++/11/streambuf:41,
                 from /usr/include/c++/11/bits/streambuf_iterator.h:35,
                 from /usr/include/c++/11/iterator:66,
                 from /usr/include/boost/concept_check.hpp:22,
                 from /usr/include/boost/range/concepts.hpp:19,
                 from /home/chuan/Downloads/gtsam-4.2/gtsam/base/types.h:24,
                 from /home/chuan/Downloads/gtsam-4.2/gtsam/global_includes.h:22,
                 from /home/chuan/Downloads/gtsam-4.2/gtsam/base/Vector.h:28,
                 from /home/chuan/Downloads/gtsam-4.2/wrap/matlab.h:25,
                 from /home/chuan/Downloads/gtsam-4.2/build/wrap/gtsam/gtsam_wrapper.cpp:1:
/usr/include/c++/11/bits/stl_pair.h:245:26: note: candidate: ‘template<class _U1, class _U2, typename std::enable_if<std::__and_<std::is_default_constructible<_U1>, std::is_default_constructible<_U2>, std::__not_<std::__and_<std::__is_implicitly_default_constructible<_U1>, std::__is_implicitly_default_constructible<_U2> > > >::value, bool>::type <anonymous> > constexpr std::pair<_T1, _T2>::pair() [with _U1 = _U1; _U2 = _U2; typename std::enable_if<std::__and_<std::is_default_constructible<_U1>, std::is_default_constructible<_U2>, std::__not_<std::__and_<std::__is_implicitly_default_constructible<_U1>, std::__is_implicitly_default_constructible<_U2> > > >::value, bool>::type <anonymous> = <anonymous>; _T1 = gtsam::DiscreteConditional; _T2 = gtsam::DecisionTreeFactor]’
  245 |       explicit constexpr pair()
      |                          ^~~~
/usr/include/c++/11/bits/stl_pair.h:245:26: note:   template argument deduction/substitution failed:
In file included from /usr/include/boost/smart_ptr/make_shared.hpp:14,
                 from /usr/include/boost/make_shared.hpp:14,
                 from /home/chuan/Downloads/gtsam-4.2/wrap/matlab.h:41,
                 from /home/chuan/Downloads/gtsam-4.2/build/wrap/gtsam/gtsam_wrapper.cpp:1:
/usr/include/boost/smart_ptr/make_shared_object.hpp:256:5: note:   candidate expects 0 arguments, 1 provided
  256 |     ::new( pv ) T( boost::detail::sp_forward<Args>( args )... );
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/include/c++/11/bits/stl_algobase.h:64,
                 from /usr/include/c++/11/bits/char_traits.h:39,
                 from /usr/include/c++/11/string:40,
                 from /usr/include/c++/11/bits/locale_classes.h:40,
                 from /usr/include/c++/11/bits/ios_base.h:41,
                 from /usr/include/c++/11/streambuf:41,
                 from /usr/include/c++/11/bits/streambuf_iterator.h:35,
                 from /usr/include/c++/11/iterator:66,
                 from /usr/include/boost/concept_check.hpp:22,
                 from /usr/include/boost/range/concepts.hpp:19,
                 from /home/chuan/Downloads/gtsam-4.2/gtsam/base/types.h:24,
                 from /home/chuan/Downloads/gtsam-4.2/gtsam/global_includes.h:22,
                 from /home/chuan/Downloads/gtsam-4.2/gtsam/base/Vector.h:28,
                 from /home/chuan/Downloads/gtsam-4.2/wrap/matlab.h:25,
                 from /home/chuan/Downloads/gtsam-4.2/build/wrap/gtsam/gtsam_wrapper.cpp:1:
/usr/include/c++/11/bits/stl_pair.h:232:26: note: candidate: ‘template<class _U1, class _U2, typename std::enable_if<std::__and_<std::__is_implicitly_default_constructible<_U1>, std::__is_implicitly_default_constructible<_U2> >::value, bool>::type <anonymous> > constexpr std::pair<_T1, _T2>::pair() [with _U1 = _U1; _U2 = _U2; typename std::enable_if<std::__and_<std::__is_implicitly_default_constructible<_U1>, std::__is_implicitly_default_constructible<_U2> >::value, bool>::type <anonymous> = <anonymous>; _T1 = gtsam::DiscreteConditional; _T2 = gtsam::DecisionTreeFactor]’
  232 |       _GLIBCXX_CONSTEXPR pair()
      |                          ^~~~
/usr/include/c++/11/bits/stl_pair.h:232:26: note:   template argument deduction/substitution failed:
In file included from /usr/include/boost/smart_ptr/make_shared.hpp:14,
                 from /usr/include/boost/make_shared.hpp:14,
                 from /home/chuan/Downloads/gtsam-4.2/wrap/matlab.h:41,
                 from /home/chuan/Downloads/gtsam-4.2/build/wrap/gtsam/gtsam_wrapper.cpp:1:
/usr/include/boost/smart_ptr/make_shared_object.hpp:256:5: note:   candidate expects 0 arguments, 1 provided
  256 |     ::new( pv ) T( boost::detail::sp_forward<Args>( args )... );
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/include/c++/11/bits/stl_algobase.h:64,
                 from /usr/include/c++/11/bits/char_traits.h:39,
                 from /usr/include/c++/11/string:40,
                 from /usr/include/c++/11/bits/locale_classes.h:40,
                 from /usr/include/c++/11/bits/ios_base.h:41,
                 from /usr/include/c++/11/streambuf:41,
                 from /usr/include/c++/11/bits/streambuf_iterator.h:35,
                 from /usr/include/c++/11/iterator:66,
                 from /usr/include/boost/concept_check.hpp:22,
                 from /usr/include/boost/range/concepts.hpp:19,
                 from /home/chuan/Downloads/gtsam-4.2/gtsam/base/types.h:24,
                 from /home/chuan/Downloads/gtsam-4.2/gtsam/global_includes.h:22,
                 from /home/chuan/Downloads/gtsam-4.2/gtsam/base/Vector.h:28,
                 from /home/chuan/Downloads/gtsam-4.2/wrap/matlab.h:25,
                 from /home/chuan/Downloads/gtsam-4.2/build/wrap/gtsam/gtsam_wrapper.cpp:1:
/usr/include/c++/11/bits/stl_pair.h:315:17: note: candidate: ‘std::pair<_T1, _T2>::pair(std::pair<_T1, _T2>&&) [with _T1 = gtsam::DiscreteConditional; _T2 = gtsam::DecisionTreeFactor]’
  315 |       constexpr pair(pair&&) = default;         ///< Move constructor
      |                 ^~~~
/usr/include/c++/11/bits/stl_pair.h:315:22: note:   no known conversion for argument 1 from ‘std::pair<boost::shared_ptr<gtsam::DiscreteConditional>, boost::shared_ptr<gtsam::DecisionTreeFactor> >’ to ‘std::pair<gtsam::DiscreteConditional, gtsam::DecisionTreeFactor>&&’
  315 |       constexpr pair(pair&&) = default;         ///< Move constructor
      |                      ^~~~~~
/usr/include/c++/11/bits/stl_pair.h:314:17: note: candidate: ‘std::pair<_T1, _T2>::pair(const std::pair<_T1, _T2>&) [with _T1 = gtsam::DiscreteConditional; _T2 = gtsam::DecisionTreeFactor]’
  314 |       constexpr pair(const pair&) = default;    ///< Copy constructor
      |                 ^~~~
/usr/include/c++/11/bits/stl_pair.h:314:22: note:   no known conversion for argument 1 from ‘std::pair<boost::shared_ptr<gtsam::DiscreteConditional>, boost::shared_ptr<gtsam::DecisionTreeFactor> >’ to ‘const std::pair<gtsam::DiscreteConditional, gtsam::DecisionTreeFactor>&’
  314 |       constexpr pair(const pair&) = default;    ///< Copy constructor
      |                      ^~~~~~~~~~~
make[2]: *** [matlab/CMakeFiles/gtsam_matlab_wrapper.dir/build.make:95: matlab/CMakeFiles/gtsam_matlab_wrapper.dir/__/wrap/gtsam/gtsam_wrapper.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:32558: matlab/CMakeFiles/gtsam_matlab_wrapper.dir/all] Error 2

### PR DESCRIPTION
**Pull request by varunagrawal**
- Fix matlab wrapping
- Update Issue Template
- Make `hub_push.sh` executable
- Make `chi_squared_quantile` inline to avoid multiple definitions error.
- Remove redundant assignment in `NonlinearConjugateGradientOptimizer`.

### CODE REVIEW

File: gtsam/linear/PCGSolver.h [hunk 1]
```diff
@@ -42,7 +42,7 @@ struct GTSAM_EXPORT PCGSolverParameters : public ConjugateGradientParameters {
   PCGSolverParameters() {}
 
   PCGSolverParameters(
-      const std::shared_ptr<PreconditionerParameters> &preconditioner)
+      const std::shared_ptr<PreconditionerParameters> preconditioner)
```
Comment (dellaert) [inline gtsam/linear/PCGSolver.h]: Why? Not in PR comment and not backward compatible

Comment (varunagrawal) [reply gtsam/linear/PCGSolver.h]: Backwards compatibility is not an issue here since I introduced this constructor last week. If the Matlab wrapper compiles, I'll add the reference & back.

Comment (varunagrawal) [reply gtsam/linear/PCGSolver.h]: Also does a reference to a shared_ptr make sense? The pointer itself is a "reference" and by passing it by value, we encourage the method scope to have ownership and keep the underlying object alive.

Comment (dellaert) [reply gtsam/linear/PCGSolver.h]: Is it depends on what you want. If you want the underlying object to keep a shared pointer until it is deleted you pass by value; if you know that method will just use the value but has no use for afterwards you pass a reference.

**Review by dellaert — APPROVED** [review]
