### PR TITLE
Fix rekey of LinearContainerFactor

### LINKED ISSUE #568: LinearFactorContainer rekey()
Hi all, 

It appears that the LinearFactorContainer has a broken rekey member function (inherited from NonlinearFactor).  

## Description

Upon construction, the LinearFactorContainer sets its keys attribute (inherited from NonlinearFactor) and stores a shared pointer to the linear factor:
https://github.com/borglab/gtsam/blob/develop/gtsam/nonlinear/LinearContainerFactor.cpp#L31

Then when NonlinearFactor's rekey function is called, the NonlinearFactor keys attribute is modified without also rekeying the stored factor.

Note the L2 vs L4 key difference in the image below:

failed_rekey

## Steps to reproduce

1. Create a LinearFactorContainer
2. Call its rekey() member function

## Expected behavior

The LinearFactorContainer should rekey its stored factor.

## Environment

C++, Ubuntu 20.04, stock gtsam 4.1 commit: 76a30a208a967634bcd33b530e7e74a5cd6aa7f3

### PR DESCRIPTION
**Pull request by varunagrawal**
As per #568, `LinearContainerFactor`'s rekey method fails because the `rekey` method doesn't update the keys for the Gaussian Factor and Linearization point properties.

This PR fixes #568 by overriding `rekey` and doing the necessary updates.

### CODE REVIEW

File: gtsam/nonlinear/LinearContainerFactor.cpp [hunk 1]
```diff
@@ -164,6 +164,47 @@ NonlinearFactor::shared_ptr LinearContainerFactor::negateToNonlinear() const {
...
+      newLinearizationPoint.insert(mapping->second, linearizationPoint_->at(mapping->first));
+  }
+  new_factor->linearizationPoint_ = newLinearizationPoint;
+
+  // upcast back and return
+  return boost::static_pointer_cast<NonlinearFactor>(new_factor);
+}
+
+/* ************************************************************************* */
+NonlinearFactor::shared_ptr LinearContainerFactor::rekey(
```
Comment (ProfFan) [inline gtsam/nonlinear/LinearContainerFactor.cpp:189]: Maybe we can just reuse the method for `std::map` here?

**Review by ProfFan — APPROVED** [review]
LGTM

**Comment by dellaert** [comment]
I’m ok if this fixes a bug , but I do want to note, for the record, that “are-keying” goes against the functional nature of GTSAM. I question the need for it and would recommend people using this to re-examine why they’re using it :-) Try to be functional unless it is *really* affecting performance.

File: gtsam/nonlinear/LinearContainerFactor.cpp (hunk 1 above)
Comment (varunagrawal) [reply gtsam/nonlinear/LinearContainerFactor.cpp:189]: Can you please explain more?

**Comment by varunagrawal** [comment]
@pshea76 check out @dellaert's comment, that's great advice right there.

File: gtsam/nonlinear/LinearContainerFactor.cpp (hunk 1 above)
Comment (varunagrawal) [reply gtsam/nonlinear/LinearContainerFactor.cpp:189]: Oh I understand now. I don't think that is doable, because the `std::map` version is doing a replacement, while the other one is doing an update. The assignment in the `KeyVector` version makes it cleaner and I am not sure how we would create the map without making some assumptions about what the user intended.
