### PR TITLE
Fix/matlab wrapper

### LINKED ISSUE #405: MATLAB Toolbox Build Broken
The build of the MATLAB toolbox (at least on Windows) is currently broken. The errors are

```
Error	LNK2019	unresolved external symbol "__declspec(dllimport) public: void __cdecl gtsam::BayesNet<class gtsam::DiscreteConditional>::print(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,class boost::function<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > __cdecl(unsigned __int64)> const &)const " (__imp_?print@?$BayesNet@VDiscreteConditional@gtsam@@@gtsam@@QEBAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@AEBV?$function@$$A6A?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@_K@Z@boost@@@Z) referenced in function main	DiscreteBayesNetExample	C:\Mike\Work\Build\gtsam\examples\DiscreteBayesNetExample.obj	1
```

```

Error	LNK2019	unresolved external symbol "__declspec(dllimport) public: void __cdecl gtsam::BayesNet<class gtsam::DiscreteConditional>::print(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,class boost::function<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > __cdecl(unsigned __int64)> const &)const " (__imp_?print@?$BayesNet@VDiscreteConditional@gtsam@@@gtsam@@QEBAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@AEBV?$function@$$A6A?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@_K@Z@boost@@@Z) referenced in function main	HMMExample	C:\Mike\Work\Build\gtsam\examples\HMMExample.obj	1	

```

```
Error	C2664	'int boost::mpl::assertion_failed<false>(boost::mpl::assert<false>::type)': cannot convert argument 1 from 'boost::mpl::failed ************boost::serialization::is_wrapper<T>::* ***********' to 'boost::mpl::assert<false>::type'	gtsam_matlab_wrapper	C:\local\boost_1_73_0\boost\archive\basic_xml_oarchive.hpp	89	
```

```
Error	C2789	'mpl_assertion_in_line_40': an object of const-qualified type must be initialized	gtsam_matlab_wrapper	C:\local\boost_1_73_0\boost\archive\basic_xml_oarchive.hpp	89	

```

The last two are weird and might be bogus -- I wouldn't be shocked if they went away after fixing the first two.

### PR DESCRIPTION
**Pull request by dellaert**
Hopefully this fixes #405 , thanks @mikesheffler

### CODE REVIEW

File: gtsam/base/Matrix.h [hunk 1]
```diff
@@ -610,5 +610,11 @@ namespace boost {
       split_free(ar, m, version);
     }
 
+    // specialized to Matrix for MATLAB wrapper
```
Comment (varunagrawal) [inline gtsam/base/Matrix.h:613]: :+1:
