### PR TITLE
replace deprecated tbb functionality

### LINKED ISSUE #208: TBB Deprecation Warnings
## Description

TBB has been updated and now when building gtsam the build output is cluttered with deprecation warnings.
```
[ 42%] Building CXX object gtsam/CMakeFiles/gtsam.dir/symbolic/SymbolicEliminationTree.cpp.o
In file included from /home/acxz/vcs/git/github/acxz/gtsam/gtsam/base/treeTraversal/parallelTraversalTasks.h:25,
                 from /home/acxz/vcs/git/github/acxz/gtsam/gtsam/base/treeTraversal-inst.h:19,
                 from /home/acxz/vcs/git/github/acxz/gtsam/gtsam/inference/EliminationTree-inst.h:25,
                 from /home/acxz/vcs/git/github/acxz/gtsam/gtsam/symbolic/SymbolicEliminationTree.cpp:19:
/usr/include/tbb/task.h:21:139: note: #pragma message: TBB Warning: tbb/task.h is deprecated. For details, please see Deprecated Features appendix in the TBB reference manual.
   21 | #pragma message("TBB Warning: tbb/task.h is deprecated. For details, please see Deprecated Features appendix in the TBB reference manual.")
      |                                                                                                                                           ^
```

## Steps to reproduce

1. git clone https://github.com/borglab/gtsam
2. mkdir build && cd build && cmake .. && make

## Expected behavior

No TBB deprecation warnings.

## Environment

OS: ArchLinux
GTSAM version: latest `develop` branch (https://github.com/borglab/gtsam/commit/7ebfdadb2840949baac5d3b096459c5168d73d00) at time of posting
TBB version: 2020.2

## Additional information

Some helpful information on fixing this issue: https://github.com/oneapi-src/oneTBB/issues/243

### PR DESCRIPTION
**Pull request by acxz**
resolves #208 continuation of #336 

I was able to replace the creation of the old api tasks with functors being passed into task_groups.

Since this is a change to core functionality, I urge people to review and check unit tests thoroughly.

### CODE REVIEW

**Comment by acxz** [comment]
I ran the unit tests 100 times and one particular test (`testGncOptimizer`) fails 1/100 with: `gtsam/tests/testGncOptimizer.cpp:713: Failure: "Exception: map::at"`

Probably a type error? I wonder if this happens with the existing codebase. Seems like an unrelated error and a bit rough to debug as it happens so infrequently.

**Comment by varunagrawal** [comment]
I was hoping you'd just update #742 rather than open a new PR, but whatever gets this resolved. :)

**Comment by ProfFan** [comment]
Maybe enable core dump by `ulimit -c unlimited` and rerun it? @acxz

**Comment by varunagrawal** [comment]
@acxz I remember seeing a comment from you on an updated guide to the new TBB API. Can you please link it here as well as add it to the README?

File: gtsam/base/treeTraversal/parallelTraversalTasks.h [hunk 1]
```diff
@@ -34,89 +34,79 @@ namespace gtsam {
...
         const boost::shared_ptr<NODE>& treeNode;
         boost::shared_ptr<DATA> myData;
         VISITOR_PRE& visitorPre;
         VISITOR_POST& visitorPost;
         int problemSizeThreshold;
+        tbb::task_group& tg;
         bool makeNewTasks;
 
-        bool isPostOrderPhase;
+        mutable bool isPostOrderPhase;
```
Comment (varunagrawal) [inline gtsam/base/treeTraversal/parallelTraversalTasks.h:48]: Add a comment about this?

File: gtsam/base/treeTraversal/parallelTraversalTasks.h [hunk 2]
```diff
@@ -34,89 +34,79 @@ namespace gtsam {
...
                 }
+                ctg.wait();
 
-                // If we have child tasks, start subtasks and wait for them to complete
-                set_ref_count((int)treeNode->children.size());
-                spawn(childTasks);
-                return firstChild;
+                // Allocate post-order task as a continuation
+                isPostOrderPhase = true;
+                tg.run(*this);
```
Comment (varunagrawal) [inline gtsam/base/treeTraversal/parallelTraversalTasks.h:93]: Ah I see. Very cool @acxz!!

**Review by varunagrawal — COMMENTED** [review]
This is amazing! Very clean PR.

I would like more comments in the code explaining as well as a link to the TBB API guide in a README file. Please do that and I will gladly approve. Again, great job!!!

**Comment by acxz** [comment]
> Can you please link it here

What I linked was a migration guide: https://docs.oneapi.com/versions/latest/onetbb/tbb_userguide/Migration_Guide/Task_API.html

The TBB docs are here: https://software.intel.com/content/www/us/en/develop/documentation/onetbb-documentation/top.html

> add it to the README

I really dont think it adding the migration guide or the docs to the README is beneficial (seems out of place), if you want I can add the migration guide to the commit message as I believe that is more appropriate.

**Comment by varunagrawal** [comment]
Yeah good point. I was thinking about what if we wanted to add more tbb based constructs. The links you added above should be fine.

File: gtsam/base/treeTraversal/parallelTraversalTasks.h (hunk 1 above)
Comment (acxz) [reply gtsam/base/treeTraversal/parallelTraversalTasks.h:48]: I think this is pretty self-explanatory and the variable is aptly named in the first place.
`isPostOrderPhase` is a variable that we want to change even in a `const` function.

I've kept the same comments throughout the code as before so I believe it is sufficient.
I'll add a message in the commit tho.

Comment (varunagrawal) [reply gtsam/base/treeTraversal/parallelTraversalTasks.h:48]: Easy for you to say, but what about the next student who comes and looks at this 2 years later?

A simple comment on what does mutable do and what's the variable used for should suffice. The amount of keystrokes you spent adding the comment above, you could have used in adding the code comment. :)

Plus, there's no such thing as too much documentation.

Comment (varunagrawal) [reply gtsam/base/treeTraversal/parallelTraversalTasks.h:48]: Also, comments in commit messages help no one especially if the person who made those commits decides to move on to other things. GTSAM gets many commits so it is easy to lose track.

Comment (acxz) [reply gtsam/base/treeTraversal/parallelTraversalTasks.h:48]: sure i'll add something

Comment (acxz) [reply gtsam/base/treeTraversal/parallelTraversalTasks.h:49]: let me know if you think it is appropriate

**Comment by dellaert** [comment]
Is this a breaking version if somebody has an old tbb version? Is it listed in the documentation what version of tbb  we need? Is that version available on all platforms?

**Review by dellaert — APPROVED** [review]

**Comment by varunagrawal** [comment]
@dellaert as a reference, the CI currently uses TBB 4.4 (aka the older version). Since the CI passes, we are good to go in terms of backwards-compatibility.

Thanks for the great work @acxz!

**Comment by ProfFan** [comment]
@acxz Could you create a quick PR to revert this? Thanks :)
