### PR TITLE
boost::optional<const Ordering &>

### LINKED ISSUE #148: Build fails: error: static_assert failed due to requirement 'boost::is_lvalue_reference<const gtsam::Scatter &&>::value' "binding rvalue references to optional lvalue references is disallowed"
```
In file included from /usr/local/include/boost/optional/optional.hpp:1468:
/usr/local/include/boost/optional/detail/optional_reference_spec.hpp:32:5: error: static_assert failed due to requirement 'boost::is_lvalue_reference<const gtsam::Scatter &&>::value' "binding rvalue references to optional lvalue references is disallowed"
    BOOST_STATIC_ASSERT_MSG(boost::is_lvalue_reference<From>::value, 
    ^                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/local/include/boost/static_assert.hpp:31:45: note: expanded from macro 'BOOST_STATIC_ASSERT_MSG'
#     define BOOST_STATIC_ASSERT_MSG( ... ) static_assert(__VA_ARGS__)
                                            ^             ~~~~~~~~~~~
/usr/local/include/boost/optional/detail/optional_reference_spec.hpp:184:54: note: in instantiation of function template specialization 'boost::detail::prevent_binding_rvalue<const gtsam::Scatter &&>' requested here
    optional(T&& /* rhs */) BOOST_NOEXCEPT { detail::prevent_binding_rvalue<T&&>(); }
                                                     ^
/usr/local/include/boost/smart_ptr/make_shared_object.hpp:256:20: note: in instantiation of member function 'boost::optional<const gtsam::Scatter &>::optional' requested here
    ::new( pv ) T( boost::detail::sp_forward<Args>( args )... );
                   ^
/usr/ports/misc/gtsam/work/gtsam-3.2.3/gtsam/linear/HessianFactor.cpp:628:26: note: in instantiation of function template specialization 'boost::make_shared<gtsam::HessianFactor, const gtsam::GaussianFactorGraph &, gtsam::Scatter>' requested here
    jointFactor = boost::make_shared<HessianFactor>(factors, Scatter(factors, keys));
                         ^
1 error generated.
[153/262] /usr/bin/c++  -DBOOST_OPTIONAL_ALLOW_BINDING_TO_RVALUES -Dgtsam_EXPORTS -I/usr/ports/misc/gtsam/work/gtsam-3.2.3/CppUnitLite -I. -I/usr/ports/misc/gtsam/work/gtsam-3.2.3 -I/usr/ports/misc/gtsam/work/gtsam-3.2.3/gtsam/3rdparty/CCOLAMD/Include -I/usr/ports/misc/gtsam/work/gtsam-3.2.3/gtsam/3rdparty/UFconfig -I/usr/local/include -O2 -pipe -fno-omit-frame-pointer -fstack-protector-strong -fno-strict-aliasing -fno-omit-frame-pointer -ftemplate-depth=1024 -O3 -Wall -DNDEBUG -Wall -fPIC -MD -MT gtsam/CMakeFiles/gtsam.dir/linear/IterativeSolver.cpp.o -MF gtsam/CMakeFiles/gtsam.dir/linear/IterativeSolver.cpp.o.d -o gtsam/CMakeFiles/gtsam.dir/linear/IterativeSolver.cpp.o -c /usr/ports/misc/gtsam/work/gtsam-3.2.3/gtsam/linear/IterativeSolver.cpp
```

FreeBSD 12
clang 8

### PR DESCRIPTION
**Pull request by gchenfc**
Get rid of boost::optional, this PR is for Ordering and Scatter classes (should fix #148 ).
Replace all usages of boost::optional<\*Ordering\*> with function overloads.

compiles and passes tests, but some potentially code-breaking changes in:

- Marginals.h - order of arguments had to change since `factorization` has a default value
- EliminatableFactorGraph.h - marginalMultifrontalBayesNet and marginalMultifrontalBayesTree no longer accept `boost::none` as a placeholder to specify later arguments
- NonlinearFactorGraph.h - same deal

Notes:

- EliminateableFactorGraph.h - `orderingType` is no longer needed in function overloads that specify ordering, but I left it for the time being to avoid potential code breaking
- NonlinearOptimizerParams.h and LevenbergMarquardParams.h still have a parameter that's a boost::optional\<Ordering\> but I left it in because it's not readily handle-able by a single function overload (not sure what other code depends on it being optional)

---
This change is [Reviewable](https://reviewable.io/reviews/borglab/gtsam/156)

### CODE REVIEW

File: gtsam/linear/JacobianFactor.cpp [hunk 1]
```diff
@@ -220,60 +220,13 @@ FastVector<JacobianFactor::shared_ptr> _convertOrCastToJacobians(
...
-  const VariableSlots & variableSlots =
-      p_variableSlots ? p_variableSlots.get() : VariableSlots(graph);
+void JacobianFactor::JacobianFactorHelper(const GaussianFactorGraph& graph,
+    const FastVector<VariableSlots::const_iterator>& orderedSlots) {
 
   // Cast or convert to Jacobians
   FastVector<JacobianFactor::shared_ptr> jacobians = _convertOrCastToJacobians(
       graph);
 
-  gttic(Order_slots);
```
Comment (gchenfc) [inline gtsam/linear/JacobianFactor.cpp]: 4 new constructors (generated from combinations of 2 optional parameters) will use this same code so i moved it into a separate function, not sure why diff util didn't recognize it better

File: gtsam/nonlinear/Marginals.h [hunk 2]
```diff
@@ -55,28 +55,50 @@ class GTSAM_EXPORT Marginals {
...
+  Marginals(const NonlinearFactorGraph& graph, const Values& solution, Factorization factorization = CHOLESKY);
+
+  /** Construct a marginals class from a nonlinear factor graph.
+   * @param graph The factor graph defining the full joint density on all variables.
+   * @param solution The linearization point about which to compute Gaussian marginals (usually the MLE as obtained from a NonlinearOptimizer).
+   * @param factorization The linear decomposition mode - either Marginals::CHOLESKY (faster and suitable for most problems) or Marginals::QR (slower but more numerically stable for poorly-conditioned problems).
+   * @param ordering The ordering for elimination.
+   */
+  Marginals(const NonlinearFactorGraph& graph, const Values& solution, const Ordering& ordering, // argument order switch due to default value of factorization, potentially code breaking
+              Factorization factorization = CHOLESKY);
```
Comment (gchenfc) [inline gtsam/nonlinear/Marginals.h]: note `ordering` now comes before `factorization` because `factorization` has a default value

File: gtsam/nonlinear/NonlinearFactorGraph.cpp [hunk 3]
```diff
@@ -344,31 +344,47 @@ GaussianFactorGraph::shared_ptr NonlinearFactorGraph::linearize(const Values& li
...
   return scatter;
 }
 
 /* ************************************************************************* */
 HessianFactor::shared_ptr NonlinearFactorGraph::linearizeToHessianFactor(
-    const Values& values, boost::optional<Ordering&> ordering, const Dampen& dampen) const {
+    const Values& values, const Dampen& dampen) const {
+  KeyVector keys = values.keys();
+  Ordering defaultOrdering(keys);
+  return linearizeToHessianFactor(values, defaultOrdering, dampen);
```
Comment (gchenfc) [inline gtsam/nonlinear/NonlinearFactorGraph.cpp]: is this tactic of creating a "default" ordering inefficient compared to creating a helper function? (as I did with the rest of the PR)

File: gtsam/inference/EliminateableFactorGraph.h [hunk 4]
```diff
@@ -194,37 +215,63 @@ namespace gtsam {
...
      *  @param function Optional dense elimination function, if not provided the default will be
      *         used.
      *  @param variableIndex Optional pre-computed VariableIndex for the factor graph, if not
      *         provided one will be computed. */
     boost::shared_ptr<BayesTreeType> marginalMultifrontalBayesTree(
       boost::variant<const Ordering&, const KeyVector&> variables,
-      OptionalOrdering marginalizedVariableOrdering = boost::none,
+      const Ordering& marginalizedVariableOrdering, // this no longer takes boost::none - potentially code breaking
       const Eliminate& function = EliminationTraitsType::DefaultEliminate,
       OptionalVariableIndex variableIndex = boost::none) const;
```
Comment (gchenfc) [inline gtsam/inference/EliminateableFactorGraph.h]: potentially breaks code,
~~`marginalMultifrontalBayesTree(variables, boost::none, EliminationQR, variableIndex);`~~ now becomes
`marginalMultifrontalBayesTree(variables, EliminationQR, variableIndex);`

File: gtsam/nonlinear/NonlinearFactorGraph.cpp [hunk 5]
```diff
@@ -344,31 +344,47 @@ GaussianFactorGraph::shared_ptr NonlinearFactorGraph::linearize(const Values& li
...
+    scatter.add(key, value.dim());
   }
 
   return scatter;
 }
 
 /* ************************************************************************* */
 HessianFactor::shared_ptr NonlinearFactorGraph::linearizeToHessianFactor(
-    const Values& values, boost::optional<Ordering&> ordering, const Dampen& dampen) const {
+    const Values& values, const Dampen& dampen) const {
```
Comment (gchenfc) [inline gtsam/nonlinear/NonlinearFactorGraph.cpp]: potentially breaks code,
~~`linearizeToHessianFactor(values, boost::none, dampen)`~~ changes to
`linearizeToHessianFactor(values, dampen)`

**Comment by dellaert** [comment]
Unfortunately, API breaking/ changing is not allowed here. So we have to find another solution

File: gtsam/linear/HessianFactor.cpp [hunk 6]
```diff
@@ -250,10 +250,10 @@ HessianFactor::HessianFactor(const GaussianFactor& gf) :
 
 /* ************************************************************************* */
 HessianFactor::HessianFactor(const GaussianFactorGraph& factors,
-    boost::optional<const Scatter&> scatter) {
+    const Scatter& scatter) {
```
Comment (dellaert) [inline gtsam/linear/HessianFactor.cpp]: Are we doing scatter in this PR?

File: gtsam/linear/JacobianFactor.cpp [hunk 7]
```diff
@@ -344,6 +297,127 @@ JacobianFactor::JacobianFactor(const GaussianFactorGraph& graph,
     this->setModel(anyConstrained, *sigmas);
 }
 
+/* ************************************************************************* */
+// Order variable slots - we maintain the vector of ordered slots, as well as keep a list
+// 'unorderedSlots' of any variables discovered that are not in the ordering.  Those will then
+// be added after all of the ordered variables.
+FastVector<VariableSlots::const_iterator> orderedSlotsHelper(
```
Comment (dellaert) [inline gtsam/linear/JacobianFactor.cpp]: Did not read in detail but is this a delegated constructor pattern?

**Comment by ProfFan** [comment]
Can we have a flag that enables another overload for `boost::optional`s?

**Comment by dellaert** [comment]
> Can we have a flag that enables another overload for `boost::optional`s?

Let’s keep this PR focused...

**Comment by ProfFan** [comment]
@gchenfc We need to have API stability tests probably :(
Also, the previous `boost::Optional&`-based I/F should probably be retained with deprecated macros https://stackoverflow.com/questions/295120/c-mark-as-deprecated

**Comment by dellaert** [comment]
No, I vote not to retain them. Let's merge this once API *calls* are verified (by a detailed review, not by additional tests). Again, don't expand scope...

**Comment by ProfFan** [comment]
@dellaert I am all good with that 👍 The current testset should have already validated the API calls, but I will double check.

File: gtsam/inference/EliminateableFactorGraph.h [hunk 8]
```diff
@@ -194,37 +213,63 @@ namespace gtsam {
...
+     *  @param marginalizedVariableOrdering Ordering for the variables being marginalized out,
+     *         i.e. all variables not in \c variables.
      *  @param function Optional dense elimination function, if not provided the default will be
      *         used.
      *  @param variableIndex Optional pre-computed VariableIndex for the factor graph, if not
      *         provided one will be computed. */
     boost::shared_ptr<BayesTreeType> marginalMultifrontalBayesTree(
       boost::variant<const Ordering&, const KeyVector&> variables,
-      OptionalOrdering marginalizedVariableOrdering = boost::none,
+      const Ordering& marginalizedVariableOrdering,
```
Comment (ProfFan) [inline gtsam/inference/EliminateableFactorGraph.h]: Since this `OptionalOrdering` is in the middle of the args list we would expect people to have a slight change of their code (remove a wandering `boost::none`) @dellaert

Comment (ProfFan) [reply gtsam/inference/EliminateableFactorGraph.h]: Also no change is necessary @gchenfc, this is just a marker for blocking :)

**Comment by dellaert** [comment]
Status?

**Comment by ProfFan** [comment]
Good to go.

**Comment by dellaert** [comment]
And, @ProfFan , by "good to go" you mean : you verified it's 100% backward compatible, yes? :-)

**Comment by ProfFan** [comment]
It is 99% backward compatible due to the fact that if someone used the pattern `xxx(args, boost::none)` instead of `xxx(args)`(using the default value) then there will be an error that `boost::none` cannot be converted to `TypeOfArgument`. Otherwise it would be just fine.

**Comment by ProfFan** [comment]
BTW, this can be 100% if we retain the old `boost::Optional<T&>` interface.

**Comment by gchenfc** [comment]
Apologies for late reply, but I added deprecated overloads with `boost::none_t` to preserve this 1% of non-backwards compatibility.
For example, `xxx(args, boost::optional<>) -> xxx(args, boost::none_t)`  For example, line 328 of `EliminateableFactorGraph.h`.  I didn't think to do this until later though so I may have missed a couple.  I can go back and check again if I missed any?

**Comment by ProfFan** [comment]
@gchenfc Feel free to check and add :) Currently I have not found any issue in the current revision.
